FROM python:3.8-alpine

LABEL maintainer="Luminoleon <luminoleon@outlook.com>"

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories \
    && apk update \
    && apk add --no-cache chromium ca-certificates \
    && pip3 install --no-cache-dir pyppeteer schedule

COPY epicgames_claimer.py /

CMD [ "python3", "/epicgames_claimer.py", "--chromium-path", "/usr/bin/chromium-browser" ]
