name: Release

on:
  push:
    tags:
    - 'v*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Get current version
        id: get_version
        uses: battila7/get-version-action@v2
      -
        name: Build and push latest
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/epicgames-claimer:latest
      -
        name: Build and push current tag
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/epicgames-claimer:${{ steps.get_version.outputs.version-without-v }}
  windows:
    runs-on: windows-latest
    steps:
      -
        name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          architecture: "x64"
      -
        name: Install Python modules
        run: |
          pip install wheel 
          pip install pyppeteer schedule pyinstaller
          pyppeteer-install
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Build
        run: |
          ${pyppeteer_version} = ((pip show pyppeteer) -match "Version").split(":")[1].trim()
          ${pyppeteer_location} = ((pip show pyppeteer) -match "Location").trimStart("Location:").trim()
          pyinstaller -F --add-data "${pyppeteer_location}/pyppeteer-${pyppeteer_version}.dist-info;pyppeteer-${pyppeteer_version}.dist-info" epicgames_claimer.py
      -
        name: Move Windows version files to "EpicGames Claimer"
        run: |
          mkdir "EpicGames Claimer"
          mv $HOME/AppData/Local/pyppeteer/pyppeteer/local-chromium/*/chrome-win32 "EpicGames Claimer"
          mv dist/*.exe "EpicGames Claimer"
      -
        name: Move Python files to "epicgames-claimer"
        run: |
          mkdir epicgames-claimer
          mv *.py epicgames-claimer
          mv *.sh epicgames-claimer
          mv requirements.txt epicgames-claimer
          mv LICENSE epicgames-claimer
      -
        name: Get current version
        id: get_version
        uses: battila7/get-version-action@v2
      -
        name: Zip files
        run: |
          Compress-Archive -Path "EpicGames Claimer" -DestinationPath EpicGames-Claimer-${{ steps.get_version.outputs.version }}-Windows.zip
          Compress-Archive -Path epicgames-claimer -DestinationPath EpicGames-Claimer-${{ steps.get_version.outputs.version }}-Python.zip          
      -
        name: Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          draft: true
          prerelease: false
          title: null
          automatic_release_tag: ${{ steps.get_version.outputs.version }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            *.zip
